### ISSUE TITLE
cannot login client

### ISSUE THREAD

**Issue by tontheonelove** [freevos/vos3000#2]
when install successful   restart server  but cannot login from vos client 

error  "connecting server please wait timeout"

and check firewalld service is stoped    pls hekp 

thankyou somuch

**Comment by Nepal-Yin** [comment]
Create a bat batch file in VOS3000 2.1.8.05 installation directory.

```
@echo off
Set the JAVA_HOME = C:\Program Files (x86)\Java\jre1.8.0_221
set Path=%JAVA_HOME%\bin; %Path%
start vos3000client.exe
```

Then execute the batch file to log in.

After installing, I restart the server and the VOS client can log in.

If the client fails to perform operations, run the **/sbin/service vos3000d reparse** command over SSH to resolve the problem.
However, if you open another client, you must repeat the above command.
made a script that temporarily fixed the problem.
```
tee /opt/jkvos.sh <<-'EOF'
#!/bin/bash

vosparsw(){
     echo "PARSE_LICENSE" >> $APP_COMMAND_FILE
     /bin/chown kunshi:kunshi  $APP_COMMAND_FILE
     kill -INT $PID >/dev/null 2>&1
}

while [ true ]; do 
    /bin/sleep 5
    APP_HOME=/home/kunshi/vos3000
    APP_COMMAND_FILE=$APP_HOME/etc/runtimecommand
    PID=`cat /home/kunshi/.run/vos3000.pid`
    GUI_PORT=`cat /home/kunshi/vos3000/etc/server.conf|grep GUI_SERVER_PORT|cut -d '=' -f2`
    SER_IP=`/sbin/ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"` 
    VAR1=`netstat -ant |grep $SER_IP:$GUI_PORT |awk '{print $5}'`
    VAR2=`cat /tmp/jk`
    if [ "$VAR1" != "$VAR2" ];then
         /bin/sleep 5
         vosparsw
         /bin/sleep 15
         vosparsw
    fi
    echo -e "$VAR1" > /tmp/jk
done
EOF

chmod +x /opt/jkvos.sh
echo -e "/usr/bin/sh /opt/jkvos.sh >/dev/null 2>&1" >> /etc/rc.local
chmod +x /etc/rc.d/rc.local
```

Restart the server and perform operations on the VOS client when the server runs properly.

**Comment by ghost** [comment]
> I tried the script and it didn't work, I added a task to crontab * * * * * /sbin/service vos3000d reparse to execute it every minute to solve the problem.
