### ISSUE TITLE
I login success ,but can't operation.

### ISSUE THREAD

**Issue by zygzx** [freevos/vos3000#3]

**Comment by zygzx** [comment]
click  menu of right have not action.

**Comment by Nepal-Yin** [comment]
You need to log in to the client first, then log in to the server using SSH, and press the **/sbin/service vos3000d reparse** command.

**Comment by north9527** [comment]
> You need to log in to the client first, then log in to the server using SSH, and press the **/sbin/service vos3000d reparse** command.

hi, How do I register for Vos3000 2.1.8.05
thanks
